apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: console.curiosityworks.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  number: 80