apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librespeed
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: librespeed.curiosityworks.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librespeed
                port:
                  number: 80
  tls:
  - hosts:
    - librespeed.curiosityworks.org
    secretName: {{ .Values.secretName }}                  