---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode-{{.Release.Name}}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: vscode-go-{{.Release.Name}}.{{.Values.domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vscode-{{.Release.Name}}
            port: 
              number: 80
  tls:
  - hosts:
    - vscode-go-{{.Release.Name}}.{{.Values.domain}}
    secretName: {{.Values.secretName}}