apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-{{ .Release.Name }}
  labels:
    app: website-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: website-{{ .Release.Name }}
    spec:
      containers:
      - name: website-{{ .Release.Name }}
        image: curiosinauts/website:{{ .Chart.AppVersion }}
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/mnt/data/www"
            name: data
      dnsPolicy: Default 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName:  {{ .Values.existingClaimNFSOnHost }}