---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-{{.Release.Name}}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: www.curiosityworks.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website-{{.Release.Name}}
            port: 
              number: 80
  tls:
  - hosts:
    - www.curiosityworks.org
    secretName: {{.Values.secretName}}