---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-{{.Release.Name}}
spec:
  selector:
    app: filebrowser-{{.Release.Name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080